refactor: comment out unused workflow steps and dependencies in Docker CI configuration

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -51,78 +51,84 @@ on:
         description: 'Dry run'
 
 jobs:
-  check-tag:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Input parameters
-        run: |
-          echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
-          echo "Java version: ${{ github.event.inputs.java-version }}" >> $GITHUB_STEP_SUMMARY
+  # check-tag:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Input parameters
+  #       run: |
+  #         echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
+  #         echo "Java version: ${{ github.event.inputs.java-version }}" >> $GITHUB_STEP_SUMMARY
 
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Check if tag exists
-        id: check_tag
-        uses: netcracker/qubership-workflow-hub/actions/tag-checker@main
-        with:
-          tag: 'v${{ github.event.inputs.version }}'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Check if tag exists
+  #       id: check_tag
+  #       uses: netcracker/qubership-workflow-hub/actions/tag-checker@main
+  #       with:
+  #         tag: 'v${{ github.event.inputs.version }}'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Output result
-        run: |
-          echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"
-          echo "Tag name: v${{ github.event.inputs.version }}"
+  #     - name: Output result
+  #       run: |
+  #         echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"
+  #         echo "Tag name: v${{ github.event.inputs.version }}"
 
-      - name: Fail if tag exists
-        if: steps.check_tag.outputs.exists == 'true'
-        run: |
-          echo "Tag already exists: v${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
-          echo "Tag already exists: v${{ github.event.inputs.version }}"
-          exit 1
+  #     - name: Fail if tag exists
+  #       if: steps.check_tag.outputs.exists == 'true'
+  #       run: |
+  #         echo "Tag already exists: v${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
+  #         echo "Tag already exists: v${{ github.event.inputs.version }}"
+  #         exit 1
 
   update-pom-version:
-    needs: [check-tag]
+    # needs: [check-tag]
     runs-on: ubuntu-latest
-    outputs:
-      artifact_id: ${{ steps.config.outputs.artifact_id }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
-      - name: Update pom.xml
-        id: config
-        uses: netcracker/qubership-workflow-hub/actions/pom-updater@main
-        with:
-          path: //p:project/p:version
-          new_value: ${{ github.event.inputs.version }}
+      - name: Update version
+        run: |
+          mvn versions:set -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
+          echo "artifact_id=dbaas" >> $GITHUB_ENV
+        
+    # outputs:
+    #   artifact_id: ${{ steps.config.outputs.artifact_id }}
+    # steps:
+    #   - name: Checkout code
+    #     uses: actions/checkout@v4
+    #     with:
+    #       fetch-depth: 0
 
-      - name: Commit Changes
-        uses: netcracker/qubership-workflow-hub/actions/commit-and-push@main
-        with:
-          commit_message: "Update pom.xml version to ${{ github.event.inputs.version }}"
+    #   - name: Update pom.xml
+    #     id: config
+    #     uses: netcracker/qubership-workflow-hub/actions/pom-updater@main
+    #     with:
+    #       path: //p:project/p:version
+    #       new_value: ${{ github.event.inputs.version }}
 
-  mvn-package:
-    needs: [update-pom-version]
-    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
-    with:
-      maven-command: "--batch-mode package -Dgpg.skip=true"
-      java-version: ${{ github.event.inputs.java-version }}
-      upload-artifact: true
-      artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
-      server-id: ${{ github.event.inputs.mode }}
-    secrets:
-      maven-token: ${{ secrets.GITHUB_TOKEN }}
-      # maven-username: ${{ secrets.MAVEN_USER }}
-      # maven-token: ${{ secrets.MAVEN_PASSWORD }}
-      # gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
-      # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
+    #   - name: Commit Changes
+    #     uses: netcracker/qubership-workflow-hub/actions/commit-and-push@main
+    #     with:
+    #       commit_message: "Update pom.xml version to ${{ github.event.inputs.version }}"
+
+  # mvn-package:
+  #   needs: [update-pom-version]
+  #   uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
+  #   with:
+  #     maven-command: "--batch-mode package -Dgpg.skip=true"
+  #     java-version: ${{ github.event.inputs.java-version }}
+  #     upload-artifact: true
+  #     # artifact-id: // ${{ needs.update-pom-version.outputs.artifact_id }}
+  #     artifact-id: "dbaas"
+  #     server-id: ${{ github.event.inputs.mode }}
+  #   secrets:
+  #     maven-token: ${{ secrets.GITHUB_TOKEN }}
 
   tests:
-    needs: [mvn-package]
+    # needs: [mvn-package]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -131,45 +137,45 @@ jobs:
       - name: Run tests
         run: echo "Running tests here"
 
-  tag:
-    needs: [tests]
-    uses: netcracker/qubership-workflow-hub/.github/workflows/tag-creator.yml@main
-    with:
-      tag-name: "v${{ github.event.inputs.version }}"
+  # tag:
+  #   needs: [tests]
+  #   uses: netcracker/qubership-workflow-hub/.github/workflows/tag-creator.yml@main
+  #   with:
+  #     tag-name: "v${{ github.event.inputs.version }}"
 
-  check-dockerfile:
-    runs-on: ubuntu-latest
-    needs: [update-pom-version, tag]
-    outputs:
-      dockerfile_exists: ${{ steps.check_dockerfile.outputs.df_exists }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: "Check Dockerfile existence"
-        id: check_dockerfile
-        shell: bash
-        run: |
-          if [[ -f Dockerfile ]]; then
-            echo "df_exists=exists" >> "$GITHUB_OUTPUT"
-          else
-            echo "Dockerfile does not exist. Docker build stage will be skipped"
-            echo "df_exists=notexists" >> "$GITHUB_OUTPUT"
-          fi
-          echo "GITHUB_OUTPUT:"
-          cat "$GITHUB_OUTPUT"
+  # check-dockerfile:
+  #   runs-on: ubuntu-latest
+  #   needs: [update-pom-version, tag]
+  #   outputs:
+  #     dockerfile_exists: ${{ steps.check_dockerfile.outputs.df_exists }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: "Check Dockerfile existence"
+  #       id: check_dockerfile
+  #       shell: bash
+  #       run: |
+  #         if [[ -f Dockerfile ]]; then
+  #           echo "df_exists=exists" >> "$GITHUB_OUTPUT"
+  #         else
+  #           echo "Dockerfile does not exist. Docker build stage will be skipped"
+  #           echo "df_exists=notexists" >> "$GITHUB_OUTPUT"
+  #         fi
+  #         echo "GITHUB_OUTPUT:"
+  #         cat "$GITHUB_OUTPUT"
 
-  docker-build-publish:
-    needs: [update-pom-version, tag, check-dockerfile]
-    if: ${{ github.event.inputs.build-docker == 'true' && needs.check-dockerfile.outputs.dockerfile_exists == 'exists' }}
-    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
-    with:
-      ref: "v${{ github.event.inputs.version }}"
-      artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
-      dry-run: ${{ inputs.dry-run }}
-      download-artifact: true
+  # docker-build-publish:
+  #   # needs: [update-pom-version, tag, check-dockerfile]
+  #   if: ${{ github.event.inputs.build-docker == 'true' && needs.check-dockerfile.outputs.dockerfile_exists == 'exists' }}
+  #   uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
+  #   with:
+  #     ref: "v${{ github.event.inputs.version }}"
+  #     artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
+  #     dry-run: ${{ inputs.dry-run }}
+  #     download-artifact: true
 
-  github-release:
-    needs: [tag]
-    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
-    with:
-      version: ${{ github.event.inputs.version }}
-      publish: false
+  # github-release:
+  #   # needs: [tag]
+  #   uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
+  #   with:
+  #     version: ${{ github.event.inputs.version }}
+  #     publish: false
